-- 000015_enforce_rls.down.sql
-- Revert FORCE RLS (back to non-enforced state for table owner)

ALTER TABLE properties NO FORCE ROW LEVEL SECURITY;
ALTER TABLE units NO FORCE ROW LEVEL SECURITY;
ALTER TABLE unit_types NO FORCE ROW LEVEL SECURITY;
ALTER TABLE guests NO FORCE ROW LEVEL SECURITY;
ALTER TABLE guest_documents NO FORCE ROW LEVEL SECURITY;
ALTER TABLE reservations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE folios NO FORCE ROW LEVEL SECURITY;
ALTER TABLE line_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE invoices NO FORCE ROW LEVEL SECURITY;
ALTER TABLE payments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE housekeeping_tasks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE laundry_orders NO FORCE ROW LEVEL SECURITY;
ALTER TABLE laundry_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE notification_templates NO FORCE ROW LEVEL SECURITY;
ALTER TABLE notification_logs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE check_in_details NO FORCE ROW LEVEL SECURITY;

-- Revoke permissions and drop role
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM stayflow_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM stayflow_app;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM stayflow_app;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM stayflow_app;
REVOKE USAGE ON SCHEMA public FROM stayflow_app;

DROP ROLE IF EXISTS stayflow_app;
